"""Client requests that add, change and delete inbounds, and their start with the core."""

import logging
from dataclasses import replace
from typing import Any

from ..cores.core_client import InboundError
from ..models.application_context import ApplicationContext
from ..models.inbound_server import InboundFieldError, InboundServer, InboundType
from ..models.serialization import JsonValue
from ..request_error import ErrorCode, RequestError, expect_fields, field_value

log = logging.getLogger(__name__)

MODEL = "inbound_server"

# Fields clients may set; type only when adding, error never.
_FIELDS = frozenset({"enabled", "proxy_listen", "proxy_port", "proxy_username", "proxy_password"})


async def start_inbound_servers(context: ApplicationContext) -> None:
    """Start every enabled stored inbound in the core; called once at startup.

    An inbound the core cannot start keeps the reason in its error and is
    logged; the others start anyway. Disabled inbounds get no error.
    """
    async with context.core_lock:
        for inbound in context.settings.inbound_server.get_all():
            error = None
            if inbound.enabled:
                try:
                    await context.core_client.inbound_set(inbound)
                except InboundError as failure:
                    error = str(failure)
                    log.warning("Inbound %s is not started: %s", inbound.id, error)
                except Exception:
                    error = "The core could not start the inbound"
                    log.exception("Failed to start inbound %s", inbound.id)
            context.settings.inbound_server.set_error(inbound.id, error)
    await context.sync.notify(MODEL)


async def add_inbound_server(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {type, proxy_port, enabled?, proxy_listen?, proxy_username?, proxy_password?};
    returns the id generated by the server.

    An enabled inbound starts listening in the core before it is saved; if the
    core cannot listen, nothing is saved.
    """
    expect_fields(payload, {"type"}, _FIELDS)
    name = field_value(payload, "type", str)
    try:
        inbound_type = InboundType(name)
    except ValueError:
        raise RequestError(
            ErrorCode.VALIDATION_ERROR, f"Unknown inbound type {name}", {"field": "type"}
        ) from None
    inbound = _validated(None, {"type": inbound_type, **_values(payload)})
    async with context.core_lock:
        _check_port(context, inbound)
        if inbound.enabled:
            await _start(context, inbound)
        context.settings.inbound_server.save(inbound)
    await context.sync.notify(MODEL)
    return {"id": inbound.id}


async def change_inbound_server(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {id, enabled?, proxy_listen?, proxy_port?, proxy_username?, proxy_password?};
    omitted fields keep their values, the type cannot change.

    An enabled inbound's listener is started or replaced in the core first, so
    the change also retries an inbound that failed to start; a disabled one is
    stopped. On an error the core and the store keep the previous inbound.
    Username and password null together remove authentication.
    """
    expect_fields(payload, {"id"}, _FIELDS)
    inbound_id = field_value(payload, "id", str)
    values = _values(payload)
    async with context.core_lock:
        stored = context.settings.inbound_server.get_by_id(inbound_id)
        if stored is None:
            raise RequestError(ErrorCode.NOT_FOUND, "Inbound not found", {"field": "id"})
        inbound = _validated(stored, {**values, "error": None})
        _check_port(context, inbound)
        if inbound.enabled:
            await _start(context, inbound)
        elif stored.enabled:
            await _stop(context, inbound_id)
        context.settings.inbound_server.save(inbound)
    await context.sync.notify(MODEL)
    return {}


async def delete_inbound_server(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {id}. The core stops listening first; the last inbound may be deleted too."""
    expect_fields(payload, {"id"})
    inbound_id = field_value(payload, "id", str)
    async with context.core_lock:
        stored = context.settings.inbound_server.get_by_id(inbound_id)
        if stored is None:
            raise RequestError(ErrorCode.NOT_FOUND, "Inbound not found", {"field": "id"})
        if stored.enabled:
            await _stop(context, inbound_id)
        context.settings.inbound_server.delete(inbound_id)
    await context.sync.notify(MODEL)
    return {}


def _values(payload: dict[str, JsonValue]) -> dict[str, Any]:
    """Model fields from the payload; username and password may be null."""
    values: dict[str, Any] = {}
    if "enabled" in payload:
        values["enabled"] = field_value(payload, "enabled", bool)
    if "proxy_listen" in payload:
        values["proxy_listen"] = field_value(payload, "proxy_listen", str)
    if "proxy_port" in payload:
        values["proxy_port"] = field_value(payload, "proxy_port", int)
    for name in ("proxy_username", "proxy_password"):
        if name in payload:
            values[name] = None if payload[name] is None else field_value(payload, name, str)
    return values


def _validated(stored: InboundServer | None, values: dict[str, Any]) -> InboundServer:
    """A new inbound, or the stored one with values replaced; errors name the field."""
    try:
        if stored is None:
            return InboundServer(**values)
        return replace(stored, **values)
    except InboundFieldError as error:
        raise RequestError(ErrorCode.VALIDATION_ERROR, str(error), {"field": error.field}) from None


def _check_port(context: ApplicationContext, inbound: InboundServer) -> None:
    """Reject a port of another inbound or of the core's test endpoint, enabled or not."""
    port = inbound.proxy_port
    if port is None:
        return
    if port == context.core_client.test_port:
        raise RequestError(
            ErrorCode.CONFLICT,
            f"Port {port} is used by the core for server checks",
            {"field": "proxy_port"},
        )
    for other in context.settings.inbound_server.get_all():
        if other.id != inbound.id and other.proxy_port == port:
            raise RequestError(
                ErrorCode.CONFLICT,
                f"Port {port} is used by another inbound",
                {"field": "proxy_port"},
            )


async def _start(context: ApplicationContext, inbound: InboundServer) -> None:
    """Start or replace the listener; on an error the core keeps the previous one."""
    try:
        await context.core_client.inbound_set(inbound)
    except InboundError as error:
        # A busy port conflicts with another program; a missing address is a wrong value.
        code = ErrorCode.CONFLICT if error.field == "proxy_port" else ErrorCode.VALIDATION_ERROR
        raise RequestError(code, str(error), {"field": error.field}) from None
    except Exception:
        log.exception("Failed to start inbound %s", inbound.id)
        raise RequestError(
            ErrorCode.CORE_ERROR, "The core could not start the inbound", {"id": inbound.id}
        ) from None


async def _stop(context: ApplicationContext, inbound_id: str) -> None:
    try:
        await context.core_client.inbound_delete(inbound_id)
    except Exception:
        log.exception("Failed to stop inbound %s", inbound_id)
        raise RequestError(
            ErrorCode.CORE_ERROR, "The core could not stop the inbound", {"id": inbound_id}
        ) from None
