"""Client requests that add and delete filters of outbound servers by name."""

import sqlite3

from ..models.application_context import ApplicationContext
from ..models.reg_filter import RegFilter
from ..models.serialization import JsonValue
from ..request_error import ErrorCode, RequestError, expect_fields, field_value
from .auto_connect import on_servers_changed
from .core import disconnect_filtered_server

MODEL = "reg_filter"


async def add_reg_filter(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {reg}; returns the id generated by the server.

    Servers whose names match get filtered = by_reg_filter at once: the store
    computes it on every read. The changed servers reach clients before the response.
    A connected server that matches is disconnected and auto_connect is turned off
    (disconnect_filtered_server), so nothing is connected.
    """
    expect_fields(payload, {"reg"})
    try:
        reg_filter = RegFilter(reg=field_value(payload, "reg", str))
    except ValueError as error:
        raise RequestError(ErrorCode.VALIDATION_ERROR, str(error), {"field": "reg"}) from None
    try:
        context.settings.reg_filter.add(reg_filter)
    except sqlite3.IntegrityError:
        raise RequestError(
            ErrorCode.CONFLICT, "The filter already exists", {"field": "reg"}
        ) from None
    await context.sync.notify(MODEL)
    # Before the servers are sent, so a disconnected server reaches clients in one message.
    await disconnect_filtered_server(context)
    await context.sync.notify("outbound_server")
    return {"id": reg_filter.id}


async def delete_reg_filter(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {id}. Servers no other filter matches lose by_reg_filter.

    Such a server shows its stored reason again (by_ping) or none, and may be
    chosen by auto_connect again. With the mode on and nothing connected, the
    best server is connected (auto_connect.on_servers_changed).
    """
    expect_fields(payload, {"id"})
    if not context.settings.reg_filter.delete(field_value(payload, "id", str)):
        raise RequestError(ErrorCode.NOT_FOUND, "Filter not found", {"field": "id"})
    await context.sync.notify(MODEL)
    await context.sync.notify("outbound_server")
    await on_servers_changed(context)
    return {}
