"""Client requests that add, change and delete routing rules, and their start with the core."""

import logging
from dataclasses import replace
from typing import Any

from ..models.application_context import ApplicationContext
from ..models.routing_rule import (
    RoutingAction,
    RoutingRule,
    RoutingRuleFieldError,
    placed,
    without,
)
from ..models.serialization import JsonValue
from ..request_error import ErrorCode, RequestError, expect_fields, field_value

log = logging.getLogger(__name__)

MODEL = "routing_rule"

_FIELDS = frozenset({"priority", "reg", "action"})


async def apply_routing_rules(context: ApplicationContext) -> None:
    """Give the stored rules to the core; called once at startup, before the inbounds listen.

    The rules were checked when they were saved, so an error here is the core's
    and stops the application like a core that cannot start.
    """
    async with context.core_lock:
        await context.core_client.routing_set(context.settings.routing_rule.get_all())


async def add_routing_rule(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {reg, action, priority?}; returns the id generated by the server.

    Without priority the rule goes last; with one, the rules from that priority
    on move down by one. The core applies the rules before they are saved; if
    it cannot, nothing is saved.
    """
    expect_fields(payload, {"reg", "action"}, _FIELDS)
    values = _values(payload)
    async with context.core_lock:
        rules = context.settings.routing_rule.get_all()
        values.setdefault("priority", len(rules) + 1)
        rule = _validated(None, values)
        await _save(context, rules, rule)
    await context.sync.notify(MODEL)
    return {"id": rule.id}


async def change_routing_rule(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {id, priority?, reg?, action?}; omitted fields keep their values.

    A new priority moves the rule: the rules between its old and new places
    move by one toward the old place.
    """
    expect_fields(payload, {"id"}, _FIELDS)
    rule_id = field_value(payload, "id", str)
    values = _values(payload)
    async with context.core_lock:
        rules = context.settings.routing_rule.get_all()
        stored = next((rule for rule in rules if rule.id == rule_id), None)
        if stored is None:
            raise RequestError(ErrorCode.NOT_FOUND, "Routing rule not found", {"field": "id"})
        rule = _validated(stored, values)
        if rule != stored:
            await _save(context, rules, rule)
    await context.sync.notify(MODEL)
    return {}


async def delete_routing_rule(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {id}. The rules after it move up by one."""
    expect_fields(payload, {"id"})
    rule_id = field_value(payload, "id", str)
    async with context.core_lock:
        rules = context.settings.routing_rule.get_all()
        if not any(rule.id == rule_id for rule in rules):
            raise RequestError(ErrorCode.NOT_FOUND, "Routing rule not found", {"field": "id"})
        await _set(context, without(rules, rule_id), rule_id)
        context.settings.routing_rule.delete(rule_id)
    await context.sync.notify(MODEL)
    return {}


def _values(payload: dict[str, JsonValue]) -> dict[str, Any]:
    values: dict[str, Any] = {}
    if "priority" in payload:
        values["priority"] = field_value(payload, "priority", int)
    if "reg" in payload:
        values["reg"] = field_value(payload, "reg", str)
    if "action" in payload:
        name = field_value(payload, "action", str)
        try:
            values["action"] = RoutingAction(name)
        except ValueError:
            raise RequestError(
                ErrorCode.VALIDATION_ERROR, f"Unknown action {name}", {"field": "action"}
            ) from None
    return values


def _validated(stored: RoutingRule | None, values: dict[str, Any]) -> RoutingRule:
    """A new rule, or the stored one with values replaced; errors name the field."""
    try:
        if stored is None:
            return RoutingRule(**values)
        return replace(stored, **values)
    except RoutingRuleFieldError as error:
        raise RequestError(ErrorCode.VALIDATION_ERROR, str(error), {"field": error.field}) from None


async def _save(context: ApplicationContext, rules: list[RoutingRule], rule: RoutingRule) -> None:
    """Apply the rules with this one in the core, then store it."""
    try:
        ordered = placed(rules, rule)
    except RoutingRuleFieldError as error:
        raise RequestError(ErrorCode.VALIDATION_ERROR, str(error), {"field": error.field}) from None
    if any(other.reg == rule.reg and other.id != rule.id for other in rules):
        raise RequestError(
            ErrorCode.CONFLICT, f"A rule for {rule.reg} already exists", {"field": "reg"}
        )
    await _set(context, ordered, rule.id)
    context.settings.routing_rule.save(rule)


async def _set(context: ApplicationContext, rules: list[RoutingRule], rule_id: str) -> None:
    """Replace the core's rules; on an error the core keeps the previous ones."""
    try:
        await context.core_client.routing_set(rules)
    except Exception:
        log.exception("Failed to apply routing rules for rule %s", rule_id)
        raise RequestError(
            ErrorCode.CORE_ERROR, "The core could not apply the routing rules", {"id": rule_id}
        ) from None
