"""Client requests that add and delete subscription links; a link cannot be changed."""

import sqlite3

from ..models.application_context import ApplicationContext
from ..models.serialization import JsonValue
from ..models.subscription_link import SubscriptionLink
from ..request_error import ErrorCode, RequestError, expect_fields, field_value
from ..subscription_loader import SubscriptionError
from .subscriptions import refresh_subscriptions

MODEL = "subscription_link"


def _save(context: ApplicationContext, link: SubscriptionLink) -> None:
    try:
        context.settings.subscription_link.save(link)
    except sqlite3.IntegrityError:
        raise RequestError(
            ErrorCode.CONFLICT, "Subscription URL is already used", {"field": "url"}
        ) from None


async def add_subscription_link(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {url}; returns the id generated by the server.

    Responds after all subscriptions are loaded, so the new link's servers reach
    the client first. If loading fails, the link stays saved and the error has
    code subscription_error with the new link's id and the failed subscription's id.
    """
    expect_fields(payload, {"url"})
    link = SubscriptionLink(url=field_value(payload, "url", str))
    _save(context, link)
    await context.sync.notify(MODEL)
    # A refresh that is already running read the links before this one was saved,
    # and a new refresh does not start while it runs: wait for it, then refresh.
    await context.tasks.wait("refresh_subscriptions")
    try:
        await refresh_subscriptions(context)
    except SubscriptionError as error:
        raise RequestError(
            ErrorCode.SUBSCRIPTION_ERROR,
            "The subscription link was added, but subscriptions could not be loaded",
            {"id": link.id, "failed_id": error.subscription_id},
        ) from None
    return {"id": link.id}


async def delete_subscription_link(
    context: ApplicationContext, payload: dict[str, JsonValue]
) -> dict[str, JsonValue]:
    """payload: {id}. Servers loaded from the link stay until the next refresh."""
    expect_fields(payload, {"id"})
    if not context.settings.subscription_link.delete(field_value(payload, "id", str)):
        raise RequestError(ErrorCode.NOT_FOUND, "Subscription link not found", {"field": "id"})
    await context.sync.notify(MODEL)
    return {}
